hibernate.connection.driver_class=com.mysql.cj.jdbc.Driver
hibernate.connection.url=jdbc:mysql://localhost:3306/world
hibernate.connection.username=root
hibernate.connection.password=MySql123PRO$

hibernate.hbm2ddl.auto=update
hibernate.show_sql=false

hibernate.current_session_context_class=thread
